# Assemble dist/: the game files plus only the three.js addons the game imports (and their deps).
import re, os, shutil, glob, hashlib, subprocess
root = 'vendor/three/jsm'
keep = {'.vercel', 'vercel.json'}
if os.path.isdir('dist'):
    for n in os.listdir('dist'):
        if n in keep: continue
        p = os.path.join('dist', n)
        shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)
else:
    os.makedirs('dist')
need = set()
for f in glob.glob('src/**/*.js', recursive=True):
    need |= {m for m in re.findall(r"three/addons/([A-Za-z0-9_./-]+\.js)", open(f).read())}
need, seen = list(need), set()
while need:
    f = need.pop()
    if f in seen: continue
    seen.add(f)
    for m in re.findall(r"from\s+['\"](\.[^'\"]+)['\"]", open(os.path.join(root, f)).read()):
        need.append(os.path.normpath(os.path.join(os.path.dirname(f), m)))
# three.js lives under a content-hashed folder (vendor/three-<hash>/) so /vendor/* can be cached as immutable: a three
# upgrade changes the folder name (and the importmap in index.html), never the bytes behind an already-cached URL.
V = 'dist/vendor/three'
for f in seen:
    d = os.path.join(V, 'jsm', f); os.makedirs(os.path.dirname(d), exist_ok=True); shutil.copy(os.path.join(root, f), d)
os.makedirs(V + '/build', exist_ok=True)
for f in ['three.module.js', 'three.core.js']: shutil.copy('vendor/three/build/' + f, V + '/build/' + f)
h = hashlib.sha256()
for dp, dn, fn in sorted(os.walk(V)):
    dn.sort()
    for n in sorted(fn):
        p = os.path.join(dp, n); h.update(os.path.relpath(p, V).encode()); h.update(open(p, 'rb').read())
vname = 'three-' + h.hexdigest()[:10]
os.rename(V, 'dist/vendor/' + vname)
for d in ['src', 'styles', 'assets']: shutil.copytree(d, 'dist/' + d)
html = open('index.html').read()
assert html.count('./vendor/three/') == 2, 'importmap layout changed'
open('dist/index.html', 'w').write(html.replace('./vendor/three/', './vendor/' + vname + '/'))
# Cloudflare Pages headers. No catch-all rule: matching rules' Cache-Control values are comma-joined, so each path gets
# exactly one rule (anything unlisted keeps Pages' default of revalidate on every visit).
REVAL = 'public, max-age=0, must-revalidate'
open('dist/_headers', 'w').write(f"""# generated by tools/build-dist.py
/
  Cache-Control: {REVAL}
/index.html
  Cache-Control: {REVAL}
/src/*
  Cache-Control: {REVAL}
/styles/*
  Cache-Control: {REVAL}
/vendor/*
  Cache-Control: public, max-age=31536000, immutable
/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
/assets/lightmaps/*.png
  Cache-Control: public, max-age=31536000, immutable
/assets/lightmaps/*.json
  Cache-Control: {REVAL}
/assets/stages/*
  Cache-Control: public, max-age=604800
/assets/news/*
  Cache-Control: public, max-age=604800
""")
print('dist ready:', len(seen), 'addon files,', vname)
